//this is where the json data is stored and passes data between the 2 pages.
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/map';
 
@Injectable()
export class Data {
data: any;
  constructor(public http: Http) {
    this.data = [
      {code: 1,name: 'Anderson House',profilePic: 'assets/img/anderson.png', images: [{image: "assets/img/anderson.png"}],about: '274 Rutledge Avenue, Charleston, SC 29425',content: 'The Anderson House was built by Daniel Cannon in 1802 as a gift for his daughter, and the home was used as a private residence until it was purchased by MUSC in 2002. The home is also known as the Gregg House after William Gregg, the founder of Graniteville, S.C. and the Graniteville Manufacturing Company, who owned the home from 1838 to 1855. In 2004, MUSC began a $1.2 million project to restore the home. The 7,314 square foot home was built in varied design styles, particularly in the Greek-Revival style. The Anderson House is on the National Register of Historic Places, and it now houses the Office of General Counsel. '},
      {code: 2,name: 'Baruch Auditorium',profilePic: 'assets/img/BaruchAuditorium002.png', images: [{image: "assets/img/BaruchAuditorium002.png"},{image:"assets/img/Baruch.png"}],about: '284 Calhoun Street, Charleston, SC 29425',content: 'Baruch Auditorium was built in 1940 as part of MUSC’s “quadrangle” of buildings, which included the 1914 Building , and others that have since been demolished or repurposed. It is named in honor of Dr. Simon Baruch, whose son, New York financier Bernard Baruch, paid for its construction. It is used as classroom lecture space. In 1940 Mr. Bernard M. Baruch donated to the College the sum of $125,000 to construct the Simon Baruch Memorial Auditorium, reconstruct the interior of the main building, and extend the library and pathology building.'},
	{code: 3,name: 'Basic Sciences Building',profilePic: 'assets/img/BSB_2.png', images: [{image: "assets/img/BSB_2.png"},{image:"assets/img/BSB_1.png"},{image:"assets/img/BasicSciencesCDMBuilding.png"}],about: 'Ashley Ave, Charleston, SC 29425',content: 'Built between 1968 and 1971, the Basic Science Building, or BSB, houses not only basic science laboratories, but also the Medical University of South Carolina’s College of Graduate Studies and the College of Dental Medicine, the only dental school in South Carolina.  The construction of the building on the site of the former Porter Military Academys Porter and Summerall Halls was initially delayed when it was discovered that the site was (until 1825) a former potter’s field, a commoner’s graveyard containing more than one hundred graves.'},
  {code: 4,name: 'Colbert Education Center and Library',profilePic: 'assets/img/Colbert.png',images: [{image: "assets/img/Colbert.png"},{image:"assets/img/BasicSciencesLibrary002.png"}],about: '178 Ashley Ave, Charleston, SC 29425.',content : 'Built by Robert Hume Lucas, descendant of Jonathan Lucas - Neo-Classical, Greek Revival style - porch columns are a copy of the Tower of the Winds in Athens - donated to college  in 1977 by late Miss Margaret Wickliffe - renovated circa 1980, cost:$450k, added a kitchen - served lunch service until 12/15/2000, after which discontinued due to low utilization - leased to chef Brett McKee for use as a resaurant, 2002 - food services later run by Mediterra Catering beginning March 2004.'},
   {code: 5,name: 'Colcock Hall',profilePic: 'assets/img/Colcock.png',images: [{image: "assets/img/Colcock.png"},{image: "assets/img/Colcock_Dental_lab.png"},{image: "assets/img/ColcockCharlesJones.png"},{image: "assets/img/ColcockExt_tree.png"}],about: '104 Colcock Hall MSC - 003, Charleston, SC 29425',content : 'In 1825, the US government acquired the land bounded by Bee, Doughty, President, and Ashley streets. Between this time and 1832, architect E. B. White designed the Charleston Arsenal to be built on this property. The Confederate military overtook the area in 1860. During this occupation, the building now known as Colcock Hall was built for the manufacture of small arms and cannon repair. Along the current south wall, remnants of seven two-story arches can still be seen. These arches were once openings through which cannons could be brought for rebanding. In 1967, Rev. Anthony Porter created \"The Orphan Home and School Association of the Church of the Holy Communion\" as a home for boys orphaned by the US Civil War. Rev. Porter took the Charleston Arsenal area in 1880. The aforementioned arches of the cannon building were subsequently bricked up to create large classrooms. The school was renamed to Porter Military Academy in 1886. The cannon building was named Butler Hall, honoring the Confederate General Matthew Butler, a US Senator from SC who helped transfer the property to Porter Military Academy. In 1919, Butler Hall was renamed Colcock Hall after Charles J. Colcock, the second headmaster and rector of the academy. The Medical College of SC purchased the Porter Academy area in 1963 including Colcock Hall, Waring Library, and St. Lukes Chapel. Colcock was immediately renovated to house the new Dental School until the Basic Sciences Building was completed in 1970. Colcock Hall was again renovated in 2005-2006 and now is home to the Offices of Central Administration of MUSC, the Office of the Provost, and the Office of the President.'},
   {code: 6,name: 'College of Health Professions-Building B/Charleston High School',profilePic: 'assets/img/CHP_Night_color.png',images: [{image: "assets/img/CHP_Night_color.png"}],about: '151 Rutledge Avenue, Charleston, SC 29425',content : 'This building was originally the Charleston High School from 1922 until 1981 and the Rhett Middle School from 1982 until 1985. In 1987 MUSC bought the property and renovated and expanded the facilities. Inside the atrium is the façade of the high school, which reads: Enter to Learn, Leave to Serve.  This building is one of three occupied by the MUSC College of Health Professions. The building next door, College of Health Professions-Building B, was built new at a cost of $1.6 million. The complex was dedicated in 2006'},
   {code: 7,name: 'College of Nursing Building',profilePic: 'assets/img/CollegeofNursingBldg_clouds2.png',images: [{image: "assets/img/CollegeofNursingBldg_clouds2.png"}],about: '99 Jonathan Lucas Street, Charleston, SC 29425',content : 'On August 29, 1956 the School of Nursing Building — our present-day College of Nursing building – opened. This five-story structure combined education, recreation, and dormitory areas all under one roof. The ground floor had classrooms, offices, and a dining room. The second floor was essentially for recreation and administration. This floor was also planned for conversion to classrooms and offices as expansion continued. The upper three floors were dormitory areas with 144 beds.The construction of the building cost approximately $1 million and it was anticipated that additional stories would be added on to the building in the future. Many people are not aware that the building was actually designed in the shape of a nurse’s cap and that an impression of Florence Nightingale’s lamp appears at the top of the building. The College of Nursing Building underwent a $10 Million renovation in 2014.'},
   {code: 8,name: 'Hervey Allen Oak',profilePic: 'assets/img/HerveyAllenOak.png',images: [{image: "assets/img/HerveyAllenOak.png"}],about: '179 Ashley Avenue, Charleston, SC 29425',content : 'In 1919, poet and novelist Hervey Allen came to Charleston to teach English at Porter Military Academy. Allen’s best-known poem, “The Blindman,” was widely read and hailed as the birth of the "lost generation" of the 1920s. His novel Anthony Adverse was one of the top selling novels of the 1930s and was later made into a Warner Brothers film of the same name, starring Olivia de Havilland and Fredric March. His time in Charleston coincided with the city’s Literary Renaissance. Allen befriended Charleston writers such as DuBose Heyward, John Bennett and Laura Bragg and in 1919 he helped found the Poetry Society of South Carolina. Allen’s poem about the Porter Oak appeared in the first school annual. That same oak survives at the southwest corner of Colcock Hall.'},
   {code: 9,name: 'Hollings Cancer Center/1914 College of Medicine building',images: [{image: "assets/img/Hollings_Cancer_Center.png"},{image: "assets/img/Quadrangle.png"},{image: "assets/img/1914building.png"}],profilePic: 'assets/img/Hollings_Cancer_Center.png',about: '86 Jonathan Lucas Street, SC 29403',content: 'The Hollings Cancer Center, established in 1990, is built on location of the 1914 Medical College building when the campus relocated from its site at Queen and Franklin streets. The original Medical College of South Carolina building was built in 1826 on land donated by the City of Charleston. The 1914 building was also built on land donated by the city. The Hollings Cancer Center is named for U.S. Senator Ernest “Fritz” Hollings. The groundbreaking was in 1990 and the building opened in 1993. Originally estimated to cost $16 million, the four-story, 75,000 square foot building became a $21 million dollar funded with federal dollars. In 2001, the building was expanded; the center is currently seven stories and 118, 000 square feet. In 2005 a $39.9 million tower was added. Despite the many changes through the years, the Hollings Cancer Center maintains the original façade of the 1914 building.'},
   {code: 10,name: 'Macaulay Museum of Dental History',profilePic: 'assets/img/MacaualayMuseum.png',images: [{image: "assets/img/MacaualayMuseum.png"},{image: "assets/img/Macaulay_1.png"},{image: "assets/img/Macaulay_2.png"}],about: '175 Ashley Ave, Charleston, SC 29403',content: 'Originally built and dedicated in 1975 the Macaulay Museum of Dental History was established to house a collection of dental antiques and artifacts given to the college by Dr. Neil W. Macaulay. Dr. Macaulay and his grandfather, John Sharp, collected dental artifacts and books for over 80 years. The collection was originally housed in a small building next to Dr. Macaulay’s family home in Columbia. The museum was renovated and reopened in October 2017.'},
   {code: 11,name: 'Porcher Medicinal Garden',profilePic: 'assets/img/PMG_1.png',images: [{image: "assets/img/PMG_1.png"},{image: "assets/img/PMG_2.png"},{image: "assets/img/PorcherPortrait.png"}],about: '171 Ashley Ave, Charleston, SC 29403',content: 'The MUSC Porcher Medicinal Garden was dedicated to MUSC alumnus and professor Dr. Francis Peyre Porcher in 2012. Dr. Porcher, born in 1824, enrolled in the Medical College of the State of South Carolina in 1844. After graduating with first honors in 1847, he published his thesis “A Medico-Botanical Catalogue of the Plants and Ferns of St. John’s, Berkeley, South Carolina.” He spent two years traveling and studying in Europe before returning to Charleston, and he entered into practice. In 1852, he, with Dr. E. Belin Flagg, opened the Charleston Preparatory Medical School of the Medical College. During his time at the Medical College, Dr. Porcher held several positions and distinctions before his death in 1895. The garden houses more than forty species of plants selected from Dr. Porcher’s 1863 book Resources of the Southern Fields and Forests.'},
   {code: 12,name: 'Porter Military Academy wall',profilePic: 'assets/img/PorterMilitary2.png',images: [{image: "assets/img/PorterMilitary2.png"},{image: "assets/img/PMAAerial.png"},{image: "assets/img/PorterToomer.png"}],about: '176 Ashley Ave, Charleston, SC 29403',content: 'Erected in 1825, this wall originally surrounded the United States Arsenal. On December 30, 1860, the arsenal was surrendered to South Carolina troops, in one of the first military actions of the Civil War. It was used by the Confederate States of America Army as a foundry and arsenal until the building was reoccupied by the United States Army on February 18, 1865. In 1880, Rev. Dr. Anthony Toomer Porter, founder of the Porter Military Academy, obtained the arsenal from the Federal Government for use as a school. MUSC acquired the property in 1964.'},
   {code: 13,name: 'Sebring-Aimar House',profilePic: 'assets/img/SebringAimarHouse.png',images: [{image: "assets/img/SebringAimarHouse.png"}],about: '268 Calhoun Street, Charleston, SC 29403',content: 'Edward Sebring, president of the State Bank of South Carolina, began building the Sebring-Aimar house in 1838, and the home, built in the Greek-Revival style, was completed eight years later in 1846. During the Civil War, the Sebring home was pillaged by Federal troops under General Edward Potter. In 1882, Sebring’s wife sold the home to Charles Pons Aimar, a local pharmacist. Aimar’s family, who owned the home for six generations, sold the Sebring-Aimar house to the MUSC Health Sciences Foundation in 1983. The building was renovated from 1986-1987, but was closed in 2005 because of problems with mold and asbestos. The building was renovated again in the fall of 2014, and it now houses the Alumni and Development Center.'},
   {code: 14,name: 'Space Tree',profilePic: 'assets/img/spaceTree.png',images: [{image: "assets/img/spaceTree.png"}],about: '173 Ashley Ave, Charleston, SC 29425',content: 'This tree is believed to be a “Space Tree,” one of many trees grown from seeds flown on the space shuttle Endeavor during its June 21 through July 1, 1993 mission. This tree, along with a second sycamore, was originally planted on Arbor Day in 1994 as a part of the Charleston County School District’s “Can Do” project. The project enabled teachers and students to work directly with NASA and leading scientists on real world, hands-on science investigations. The current location is the third spot that the tree has occupied since its original planting in 1994. The relocations have slowed the tree’s growth, which explains why it is smaller in size than other trees of a similar age.'},
   {code: 15,name: 'St. Lukes Chapel',profilePic: 'assets/img/StLuke2BW.png',images: [{image: "assets/img/StLukesChapelinterior.png"},{image: "assets/img/StLukesafterHugo.png"},{image: "assets/img/StLukes_arsenal.png"}],about: '181 Ashley Ave, Charleston, SC 29425',content: 'St. Lukes Chapel sits on the site of a potters field purchased by the City of Charleston in 1807.  In 1825, the United States government acquired the property to built a federal arsenal.  Built between 1825 and 1830, the arsenal housed small arms, field artillery, and a stable.  The property was one of the first Federal properties acquired by the Confederacy during the Civil War.  After the war, it served as a military arsenal until 1879.  In 1867, the Rev. Anthony Toomer Porter founded the Holy Communion Church Institute for boys orphaned or left destitute by the Civil War.  In 1879, he acquired the arsenal and hired Holton Bell, a brick mason of African-American descent, to design and construct changes to the building to convert it into a chapel.  The roof was removed, the walls raised, a gothic roof and stained glass windows installed, and a surrounding brick wall built.  In 1886, the Holy Communication Church Institute was renamed Porter Academy, and by 1893, the school became known as the Porter Military Academy.  The chapel, known as St. Timothy’s Chapel was used every morning by the cadets, who represented all faiths.  In 1963, the Medical College of South Carolina purchased the Porter campus and the Porter Military Academy merged with the Gaud and Watts schools to become Porter-Gaud School, located west of the Ashley River.  The Medical College kept the chapel and renamed it for St. Luke, the patron saint of physicians.  On September 21, 1989, St. Luke’s Chapel was severely damaged by Hurricane Hugo.  The roof collapsed, the organ was ruined beyond repair, and the stained glass windows crashed into Bee Street.  Over $1,000,000 and four years later, the restored chapel was rededicated on February 10, 1994, a perfect combination between historical ambience and modern functionality.  A new organ was built and named in honor of Margaret Metcalf, the wife of Dr. John Fesperman, a major contributor to the construction.  The chapel is currently used for weddings, musical events, an annual memorial service to honor those who donated their bodies to science, and an annual memorial service for the Porter Military Academy Alumni Association.'},
   {code: 16,name: 'Waring Historical Library ',profilePic: 'assets/img/waring-library-porter-gaud.png',images: [{image: "assets/img/waring-library-porter-gaud.png"},{image: "assets/img/WaringLibrary1894.png"},{image: "assets/img/Waring_1.png"},{image: "assets/img/Waring_2.png"},{image: "assets/img/waring-sign.png"},{image: "assets/img/WHL_interior_upstairs.png"}],about: '181 Ashley Ave, Charleston, SC 29425',content: 'St. Lukes Chapel sits on the site of a potters field purchased by the City of Charleston in 1807.  In 1825, the United States government acquired the property to built a federal arsenal.  Built between 1825 and 1830, the arsenal housed small arms, field artillery, and a stable.  The property was one of the first Federal properties acquired by the Confederacy during the Civil War.  After the war, it served as a military arsenal until 1879.  In 1867, the Rev. Anthony Toomer Porter founded the Holy Communion Church Institute for boys orphaned or left destitute by the Civil War.  In 1879, he acquired the arsenal and hired Holton Bell, a brick mason of African-American descent, to design and construct changes to the building to convert it into a chapel.  The roof was removed, the walls raised, a gothic roof and stained glass windows installed, and a surrounding brick wall built.  In 1886, the Holy Communication Church Institute was renamed Porter Academy, and by 1893, the school became known as the Porter Military Academy.  The chapel, known as St. Timothy’s Chapel was used every morning by the cadets, who represented all faiths.  In 1963, the Medical College of South Carolina purchased the Porter campus and the Porter Military Academy merged with the Gaud and Watts schools to become Porter-Gaud School, located west of the Ashley River.  The Medical College kept the chapel and renamed it for St. Luke, the patron saint of physicians.  On September 21, 1989, St. Luke’s Chapel was severely damaged by Hurricane Hugo.  The roof collapsed, the organ was ruined beyond repair, and the stained glass windows crashed into Bee Street.  Over $1,000,000 and four years later, the restored chapel was rededicated on February 10, 1994, a perfect combination between historical ambience and modern functionality.  A new organ was built and named in honor of Margaret Metcalf, the wife of Dr. John Fesperman, a major contributor to the construction.  The chapel is currently used for weddings, musical events, an annual memorial service to honor those who donated their bodies to science, and an annual memorial service for the Porter Military Academy Alumni Association.'},
   {code: 17,name: 'Wickliffe House',profilePic: 'assets/img/Wickliffe_1.png',images: [{image: "assets/img/Wickliffe_1.png"}],about: '178 Ashley Ave, Charleston, SC 29403',content: 'Built by Robert Hume Lucas, descendant of Jonathan Lucas - Neo-Classical, Greek Revival style - porch columns are a copy of the Tower of the Winds in Athens - donated to college  in 1977 by late Miss Margaret Wickliffe - renovated circa 1980, cost:$450k, added a kitchen - served lunch service until 12/15/2000, after which discontinued due to low utilization - leased to chef Brett McKee for use as a resaurant, 2002 - food services later run by Mediterra Catering beginning March 2004 - '},
  ];
	}
 
  loadAll(){
      return Promise.resolve(this.data);
  };
  getByID(id){
    for(var i=0; i< (this.data).length; i++)
    {
      if(this.data[i].code == id)
      {
        return Promise.resolve(this.data[i]);
      }
    }
  };
}